<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/zf2 for the canonical source repository
 * @copyright Copyright (c) 2005-2012 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 * @package   Zend_Paginator
 */

namespace ZendTest\Paginator\Adapter;

use Zend\Paginator\Adapter;
use Zend\Db\Adapter as DbAdapter;
use Zend\Db\Sql;
use Zend\Paginator\Exception;

require_once __DIR__ . '/../_files/TestTable.php';

/**
 * @category   Zend
 * @package    Zend_Paginator
 * @subpackage UnitTests
 * @group      Zend_Paginator
 */
class DbSelectTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Zend\Paginator\Adapter\DbSelect
     */
    protected $_select;

    /**
     * @var \Zend\Db\Adapter\Adapter
     */
    protected $_dbAdapter;

    /**
     * @var \Zend\Db\Adapter\Adapter|Platform
     */
    protected $_platform;

    /**
     * @var \Zend\Db\Sql\Select
     */
    protected $_query;

    /**
     * @var \Zend\Db\TableGateway\TableGateway
     */
    protected $_table;

    /**
     * Prepares the environment before running a test.
     */
    protected function setUp()
    {
//        $this->markTestIncomplete('Will skip until Zend\Db is refactored.');

        if (!extension_loaded('pdo_sqlite')) {
           $this->markTestSkipped('Pdo_Sqlite extension is not loaded');
        }

        parent::setUp();

        $this->_dbAdapter = new DbAdapter\Adapter(array(
            'driver'   => 'Pdo_Sqlite',
            'database' =>  __DIR__ . '/../_files/test.sqlite',
        ));

        $this->_table = new \ZendTest\Paginator\TestAsset\TestTable('test', $this->_dbAdapter);

        $this->_query = new Sql\Select;
        $this->_query->from('test')
                     ->order('number ASC'); // ZF-3740
                     //->limit(1000, 0); // ZF-3727

        $this->_platform = new DbAdapter\Platform\Sqlite;
        $this->_select = new Adapter\DbSelect($this->_query, $this->_dbAdapter);

    }
    /**
     * Cleans up the environment after running a test.
     */
    protected function tearDown()
    {
        $this->_select = null;
        parent::tearDown();
    }

    public function testGetsItemsAtOffsetZero()
    {
        $actual = $this->_select->getItems(0, 10);

        $i = 1;
        foreach ($actual as $item) {
            $this->assertEquals($i, $item['number']);
            $i++;
        }
    }

    public function testGetsItemsAtOffsetTen()
    {
        $actual = $this->_select->getItems(10, 10);

        $i = 11;
        foreach ($actual as $item) {
            $this->assertEquals($i, $item['number']);
            $i++;
        }
    }

    public function testAcceptsIntegerValueForRowCount()
    {
        $this->_select->setRowCount(101);
        $this->assertEquals(101, $this->_select->count());
    }

    public function testThrowsExceptionIfInvalidQuerySuppliedForRowCount()
    {
        $this->setExpectedException('Zend\Paginator\Adapter\Exception\InvalidArgumentException', 'Row count column not found');
        $this->_select->setRowCount($this->_query);
    }

    public function testThrowsExceptionIfInvalidQuerySuppliedForRowCount2()
    {
        $wrongcolumn = $this->_dbAdapter->platform->quoteIdentifier('wrongcolumn');
        $expr = new Sql\Expression("COUNT(*) AS $wrongcolumn");
        $query = new Sql\Select;
        $query->columns(array($expr));
        $query->from('test');

        $this->setExpectedException('Zend\Paginator\Adapter\Exception\InvalidArgumentException', 'Row count column not found');
        $this->_select->setRowCount($query);
    }

    public function testAcceptsQueryForRowCount()
    {
        $row_count_column = $this->_dbAdapter->platform->quoteIdentifier(Adapter\DbSelect::ROW_COUNT_COLUMN);
        $expr = new Sql\Expression("COUNT(*) AS $row_count_column");

        $rowCount = clone $this->_query;
        $rowCount->columns(array($expr));

        $this->assertEquals(500, $this->_select->count());
    }

    public function testThrowsExceptionIfInvalidRowCountValueSupplied()
    {
        $this->setExpectedException('Zend\Paginator\Adapter\Exception\InvalidArgumentException', 'Invalid row count');
        $this->_select->setRowCount('invalid');
    }

    public function testReturnsCorrectCountWithAutogeneratedQuery()
    {
        $expected = 500;
        $actual = $this->_select->count();

        $this->assertEquals($expected, $actual);
    }

    public function testDbTableSelectDoesNotThrowException()
    {
        $adapter = new Adapter\DbSelect($this->_query, $this->_dbAdapter);
        $count = $adapter->count();
        $this->assertEquals(500, $count);
    }

    /**
     * @group ZF-4001
     */
    public function testGroupByQueryReturnsOneRow()
    {
        $query = new Sql\Select;
        $query->from('test')
               ->order('number ASC')
               ->limit(1000, 0)
               ->group('number');

        $adapter = new Adapter\DbSelect($query, $this->_dbAdapter);

        $this->assertEquals(500, $adapter->count());
    }

    /**
     * @group ZF-4001
     */
    public function testGroupByQueryOnEmptyTableReturnsRowCountZero()
    {
        $db = new DbAdapter\Adapter(array(
            'driver'   => 'Pdo_Sqlite',
            'database' =>  __DIR__ . '/../_files/testempty.sqlite',
        ));

        $query = new Sql\Select;
        $query->from('test')
              ->order('number ASC')
              ->limit(1000, 0);
        $adapter = new Adapter\DbSelect($query, $db);

        $this->assertEquals(0, $adapter->count());
    }

    /**
     * @group ZF-4001
     */
    public function testGroupByQueryReturnsCorrectResult()
    {
        $query = new Sql\Select;
        $query->from('test')
              ->order('number ASC')
              ->limit(1000, 0)
              ->group('testgroup');
        $adapter = new Adapter\DbSelect($query, $this->_dbAdapter);

        $this->assertEquals(2, $adapter->count());
    }

    /**
     * @group ZF-4032
     */
    public function testDistinctColumnQueryReturnsCorrectResult()
    {
        $this->markTestSkipped('Distinct not fully implemented (ZF2-424)');
        $expr = new Sql\Expression("DISTINCT testgroup ");
        $query = new Sql\Select;
        $query->from('test')
              ->columns(array($expr))
              ->order('number ASC')
              ->limit(1000, 0);
        $adapter = new Adapter\DbSelect($query, $this->_dbAdapter);

        $this->assertEquals(2, $adapter->count());
    }

    /**
     * @group ZF-4094
     */
    public function testSelectSpecificColumns()
    {
        $number = $this->_platform->quoteIdentifier('number');
        $query = new Sql\Select;
        $query->from('test')
            ->columns( array('testgroup', 'number'))
            ->where("$number >= ?", '1');

        $adapter = new Adapter\DbSelect($query, $this->_dbAdapter);

        $this->assertEquals(500, $adapter->count());
    }

    /**
     * @group ZF-4177
     */
    public function testSelectDistinctAllUsesRegularCountAll()
    {
        $this->markTestSkipped('Distinct not fully implemented (ZF2-424)');

        $expr = new Sql\Expression("DISTINCT ?", 'testgroup', array(Sql\Expression::TYPE_IDENTIFIER));
        $query = new Sql\Select;
        $query->from('test')
            ->columns(array($expr));

        $adapter = new Adapter\DbSelect($query, $this->_dbAdapter);

        $this->assertEquals(500, $adapter->count());
    }

    /**
     * @group ZF-5233
     */
    public function testSelectHasAliasedColumns()
    {
        $this->markTestSkipped('Not clear yet how to fix this');

        $db = $this->_dbAdapter;

        $db->query('DROP TABLE IF EXISTS `sandboxTransaction`');
        $db->query('DROP TABLE IF EXISTS `sandboxForeign`');

        // A transaction table
        $db->query(
            'CREATE TABLE `sandboxTransaction` (
                `id` INTEGER PRIMARY KEY,
                `foreign_id` INT( 1 ) NOT NULL ,
                `name` TEXT NOT NULL
            ) '
        );

        // A foreign table
        $db->query(
            'CREATE TABLE `sandboxForeign` (
                `id` INTEGER PRIMARY KEY,
                `name` TEXT NOT NULL
            ) '
        );

        // Insert some data
        $db->insert('sandboxTransaction',
            array(
                'foreign_id' => 1,
                'name' => 'transaction 1 with foreign_id 1',
            )
        );

        $db->insert('sandboxTransaction',
            array(
                'foreign_id' => 1,
                'name' => 'transaction 2 with foreign_id 1',
            )
        );

        $db->insert('sandboxForeign',
            array(
                'name' => 'John Doe',
            )
        );

        $db->insert('sandboxForeign',
            array(
                'name' => 'Jane Smith',
            )
        );

        $query = new Sql\Select;
        $expr = new Sql\Expression("DISTINCT name");
        $query->from(array('a'=>'sandboxTransaction'))
            ->join(array('b'=>'sandboxForeign'), 'a.foreign_id = b.id', array('name'))
            ->columns(array($expr));

// old query
//        $query = $db->select()->from(array('a'=>'sandboxTransaction'), array())
//                              ->join(array('b'=>'sandboxForeign'), 'a.foreign_id = b.id', array('name'))
//                              ->distinct(true);

        $adapter = new Adapter\DbSelect($query, $this->_dbAdapter);
        $this->assertEquals(1, $adapter->count());
    }

    /**
     * @group ZF-5956
     */
    public function testUnionSelect()
    {
        $this->markTestSkipped('Union not clear');
        $union = $this->_dbAdapter->select()->union(array(
            $this->_dbAdapter->select()->from('test')->where('number <= 250'),
            $this->_dbAdapter->select()->from('test')->where('number > 250')
        ));

        $adapter = new Adapter\DbSelect($union, $this->_dbAdapter);
        $expected = 500;
        $actual = $adapter->count();

        $this->assertEquals($expected, $actual);
    }

    /**
     * @group ZF-7045
     */
    public function testGetCountSelect()
    {
        $this->markTestSkipped('Union not clear');
        $union = $this->_dbAdapter->select()->union(array(
            $this->_dbAdapter->select()->from('test')->where('number <= 250'),
            $this->_dbAdapter->select()->from('test')->where('number > 250')
        ));

        $adapter = new Adapter\DbSelect($union, $this->_dbAdapter);

        $expected = 'SELECT COUNT(1) AS "zend_paginator_row_count" FROM (SELECT "test".* FROM "test" WHERE (number <= 250) UNION SELECT "test".* FROM "test" WHERE (number > 250)) AS "t"';

        $this->assertEquals($expected, $adapter->getCountSelect()->__toString());
    }

    /**
     * @group ZF-5295
     */
    public function testMultipleDistinctColumns()
    {
        $this->markTestSkipped('Distinct not fully implemented (ZF2-424)');

        $expr = new Sql\Expression("DISTINCT testgroup ");
        $query = new Sql\Select;
        $query->from('test')
            ->columns(array($expr, 'testgroup', 'number'));
        $adapter = new Adapter\DbSelect($query, $this->_dbAdapter);

        $expected = 'SELECT COUNT(1) AS "zend_paginator_row_count" FROM (SELECT DISTINCT "test"."testgroup", "test"."number" FROM "test") AS "t"';

        $this->assertEquals($expected, $adapter->getCountSelect()->getSqlString());
        $this->assertEquals(500, $adapter->count());
    }

    /**
     * @group ZF-5295
     */
    public function testSingleDistinctColumn()
    {
        $this->markTestSkipped('Distinct not fully implemented (ZF2-424)');
        $select = $this->_dbAdapter->select()->from('test', 'testgroup')
                                      ->distinct(true);
        $adapter = new Adapter\DbSelect($select, $this->_dbAdapter);

        $expected = 'SELECT COUNT(DISTINCT "test"."testgroup") AS "zend_paginator_row_count" FROM "test"';

        $this->assertEquals($expected, $adapter->getCountSelect()->getSqlString());
        $this->assertEquals(2, $adapter->count());
    }

    /**
     * @group ZF-6330
     * @todo: figure out subqueries
     */
    public function testGroupByMultipleColumns()
    {

        $select = new Sql\Select;
        $select->from('test')
            ->columns(array('testgroup'))
            ->group(array('number', 'testgroup'));

        $adapter = new Adapter\DbSelect($select, $this->_dbAdapter);

        $expected = 'SELECT COUNT(1) AS "zend_paginator_row_count" FROM (SELECT "test"."testgroup" FROM "test" GROUP BY "number"' . ",\n\t" . '"testgroup") AS "t"';

        $this->assertEquals($expected, $adapter->getCountSelect()->getSqlString());
        $this->assertEquals(500, $adapter->count());
    }

    /**
     * @group ZF-6330
     */
    public function testGroupBySingleColumn()
    {

        $select = new Sql\Select;
        $select->from('test')
            -> columns(array('testgroup'))
            ->group('test.testgroup');

        $adapter = new Adapter\DbSelect($select, $this->_dbAdapter);

        $expected = 'SELECT COUNT(DISTINCT "test"."testgroup") AS "zend_paginator_row_count" FROM "test"';

        $this->assertEquals($expected, $adapter->getCountSelect()->getSqlString());
        $this->assertEquals(2, $adapter->count());
    }

    /**
     * @group ZF-6562
     */
    public function testSelectWithHaving()
    {

        $select = new Sql\Select;
        $select->from('test')
            ->group('number')
            ->having('number > 250');

//        $select = $this->_dbAdapter->select()->from('test')
//                                      ->group('number')
//                                      ->having('number > 250');

        $adapter = new Adapter\DbSelect($select, $this->_dbAdapter);

        $expected = 'SELECT COUNT(1) AS "zend_paginator_row_count" FROM (SELECT "test".* FROM "test" GROUP BY "number" HAVING (number > 250)) AS "t"';

        $this->assertEquals($expected, $adapter->getCountSelect()->getSqlString());
        $this->assertEquals(250, $adapter->count());
    }

    /**
     * @group ZF-7127
     */
    public function testMultipleGroupSelect()
    {
        $select = new Sql\Select;
        $select->from('test')
            ->group('testgroup')
            ->group('number')
            ->where('number > 250');

//        $select = $this->_dbAdapter->select()->from('test')
//                                      ->group('testgroup')
//                                      ->group('number')
//                                      ->where('number > 250');

        $adapter = new Adapter\DbSelect($select, $this->_dbAdapter);

        $expected = 'SELECT COUNT(1) AS "zend_paginator_row_count" FROM (SELECT "test".* FROM "test" WHERE (number > 250) GROUP BY "testgroup"' . ",\n\t" . '"number") AS "t"';

        $this->assertEquals($expected, $adapter->getCountSelect()->getSqlString());
        $this->assertEquals(250, $adapter->count());
    }

    /**
     * @group ZF-10704
     */
    public function testObjectSelectWithBind()
    {
        $this->markTestSkipped('Distinct / union not clear');
        $select = $this->_db->select();
        $select->from('test', array('number'))
               ->where('number = ?')
               ->distinct(true)
               ->bind(array(250));

        $adapter = new Adapter\DbSelect($select, $this->_dbAdapter);
        $this->assertEquals(1, $adapter->count());

        $select->reset(Sql\Select::DISTINCT);
        $select2 = clone $select;
        $select2->reset(Sql\Select::WHERE)
                ->where('number = 500');

        $selectUnion = $this->_dbAdapter
                           ->select()
                           ->bind(array(250));

        $selectUnion->union(array($select, $select2));
        $adapter = new Adapter\DbSelect($selectUnion, $this->_dbAdapter);
        $this->assertEquals(2, $adapter->count());
    }
}
